//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,35,10,100,NORMAL
        ///Vine Whip,35,95,GRASS
        ///Razor Leaf,55,10,95,GRASS
        ///Solar Beam,120,10,100,GRASS.
        /// </summary>
        public static string Bulbasaur {
            get {
                return ResourceManager.GetString("Bulbasaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ButtonClicked {
            get {
                return ResourceManager.GetStream("ButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch,40,15,100,NORMAL
        ///Ember,40,15,100,FIRE
        ///Rage,20,15,100,NORMAL
        ///Slash,70,15,100,NORMAL
        ///Flamethrower,90,14,100,FIRE
        ///Fire Spin,35,10,85,FIRE.
        /// </summary>
        public static string Charmander {
            get {
                return ResourceManager.GetString("Charmander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,40,10,100,NORMAL
        ///Razor Leaf,55,10,95,GRASS
        ///Magical Leaf,60,10,100,GRASS
        ///Body Slam,85,10,100,NORMAL
        ///Solar Beam,120,5,100,GRASS.
        /// </summary>
        public static string Chikorita {
            get {
                return ResourceManager.GetString("Chikorita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch,40,15,100,NORMAL
        ///Ember,40,15,100,FIRE
        ///Flamethrower,90,14,100,FIRE
        ///Fire Spin,35,10,85,FIRE
        ///Power Up Punch,40,10,100,FIGHTING
        ///Fury Swipes,18,15,80,NORMAL
        ///Flame Wheel,60,10,100,FIRE
        ///Acrobatics,55,10,100,FLYING.
        /// </summary>
        public static string Chimchar {
            get {
                return ResourceManager.GetString("Chimchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,40,15,100,NORMAL
        ///Ember,40,15,100,FIRE
        ///Quick Attack,40,15,100,NORMAL
        ///Flame Wheel,60,15,100,NORMAL
        ///Lava Plume,80,15,100,FIRE
        ///Flamethrower,90,10,100,FIRE
        ///Inferno,100,5,50,FIRE
        ///Eruption,150,5,100,FIRE
        ///Burn Up,130,5,100,FIRE.
        /// </summary>
        public static string Cyndaquil {
            get {
                return ResourceManager.GetString("Cyndaquil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Evolution1 {
            get {
                return ResourceManager.GetStream("Evolution1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gtg
        ///gtgt
        ///gt
        ///gtg
        ///tg
        ///tg.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion,20,1
        ///Max Potion,500,1
        ///Hyper Potion,200,1
        ///Revive,1,1
        ///Antidote,0,1
        ///Revive,100,1
        ///Super Potion,100,1
        ///Pokéblock,20,5.
        /// </summary>
        public static string InventoryItems {
            get {
                return ResourceManager.GetString("InventoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confusion,50,15,90,PSYCHIC
        ///Ancient Power,60,15,100,ROCK
        ///Psycho Cut,70,15,95,PSYCHIC
        ///Psystrike,100,20,85,PSYCHIC.
        /// </summary>
        public static string Mewtwo {
            get {
                return ResourceManager.GetString("Mewtwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,40,10,100,NORMAL
        ///Water Gun,40,10,100,WATER
        ///Rock Smash,40,10,100,FIGHTING
        ///Rock Throw,50,10,90,ROCK
        ///Water Pulse,60,10,100,WATER
        ///Rock Slide,75,10,90,ROCK
        ///Take Down,90,10,85,NORMAL
        ///Surf,90,10,100,WATER
        ///Hydro Pump,110,5,80,WATER.
        /// </summary>
        public static string Mudkip {
            get {
                return ResourceManager.GetString("Mudkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Attack,40,10,100,Normal
        ///Thunder Shock,40,12,100,Electric
        ///Spark,65,14,100,Electric
        ///Thunderbolt,90,10,100,Electric
        ///Thunder,110,8,70,Electric
        ///Thunder Punch,75,9,100,Electric.
        /// </summary>
        public static string Pikachu {
            get {
                return ResourceManager.GetString("Pikachu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Gun,40,10,100,WATER
        ///Water Gun,40,10,100,WATER
        ///Hydro Pump,110,5,80,WATER
        ///Drill Peck,80,10,100,FLYING
        ///Whirlpool,35,10,85,WATER
        ///Brine,65,10,100,WATER
        ///Fury Attack,15,10,85,NORMAL
        ///Peck,35,10,100,FLYING
        ///Pound,40,10,100,FLYING.
        /// </summary>
        public static string Piplup {
            get {
                return ResourceManager.GetString("Piplup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,40,15,100,NORMAL
        ///Water Gun,40,15,100,WATER
        ///Rapid Spin,50,10,100,NORMAL
        ///Bite,60,15,100,DARK
        ///Water Pulse,60,15,100,WATER
        ///Aqua Tail,90,15,100,WATER
        ///Hydro Pump,110,5,90,WATER
        ///Skull Bash,130,5,100,NORMAL.
        /// </summary>
        public static string Squirtle {
            get {
                return ResourceManager.GetString("Squirtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch,40,10,100,NORMAL
        ///Ember,40,10,100,FIRE
        ///Quick Attack,40,10,100,NORMAL
        ///Flamne Charge,50,10,100,FIRE
        ///Slash,70,10,100,NORMAL
        ///Bounce,85,10,85,FLYING
        ///Flamethrower,90,10,100,FIRE
        ///Flare Blitz,120,10,100,FIRE.
        /// </summary>
        public static string Torchic {
            get {
                return ResourceManager.GetString("Torchic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch,40,10,100,NORMAL
        ///Water Gun,40,10,100,WATER
        ///Mud Slap,20,10,100,GROUND
        ///Bite,60,10,100,DARK
        ///Ice Fang,65,10,95,ICE
        ///Crunch,80,10,100,DARK
        ///Thrash,120,10,100,NORMAL
        ///Aqua Tail,90,10,90,WATER
        ///Superpower,120,5,100,FIGHTING
        ///Hydro Pump,110,5,80,WATER.
        /// </summary>
        public static string Totodile {
            get {
                return ResourceManager.GetString("Totodile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound,40,10,100,NORMAL
        ///Leafage,40,10,100,GRASS
        ///Quick Attack,40,10,100,NORMAL
        ///Mega Drain,40,10,100,GRASS
        ///Assurance,60,10,100,DARK
        ///Giga Drain,75,10,100,GRASS
        ///Slam,80,10,75,NORMAL
        ///Energy Ball,90,10,100,GRASS
        ///Leaf Storm,130,10,90,GRASS.
        /// </summary>
        public static string Treecko {
            get {
                return ResourceManager.GetString("Treecko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackle,35,10,100,NORMAL
        ///Leafage,40,10,100,GRASS
        ///Razor Leaf,55,10,95,GRASS
        ///Leaf Storm,130,10,90,GRASS
        ///Mega Drain,40,10,100,GRASS
        ///Giga Drain,75,10,100,GRASS
        ///Bite,60,10,100,DARK
        ///Crunch,80,10,100,DARK.
        /// </summary>
        public static string Turtwig {
            get {
                return ResourceManager.GetString("Turtwig", resourceCulture);
            }
        }
    }
}
