//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ButtonClicked {
            get {
                return ResourceManager.GetStream("ButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Air Slash,75,15,95,FLYING
        ///Flamethrower,90,15,100,FIRE
        ///Ember Flame,40,25,100,FIRE
        ///Metal Claw,50,25,95,STEEL
        ///Aerial Ace,60,3,100,FLYING
        ///Fire Blitz,120,10,100,FIRE
        ///Dragon Pulse,85,10,100,DRAGON
        ///Giga Impact,150,10,90,NORMAL
        ///Dragon Claw,80,10,100,DRAGON
        ///Steel Wing,70,10,90,STEEL
        ///Overheat,130,10,90,FIRE
        ///Bite,60,10,100,NORMAL
        ///Fly High,90,5,95,FLYING.
        /// </summary>
        public static string Charizard {
            get {
                return ResourceManager.GetString("Charizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dazzling Gleam,80,10,100,FAIRY
        ///Moonblast,95,10,100,FAIRY
        ///Dream Eater,100,5,100,PSYCHIC
        ///Future Sight,120,5,100,PSYCHIC
        ///Psybeam,65,10,100,PSYCHIC
        ///Confusion,50,12,100,PSYCHIC
        ///Draining Kiss,50,15,100,FAIRY
        ///Psychic,90,10,100,PSYCHIC
        ///Shadow Ball,80,10,100,GHOST.
        /// </summary>
        public static string Gardevoir {
            get {
                return ResourceManager.GetString("Gardevoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bite,60,10,100,Dark
        ///Tackle,40,10,100,Normal
        ///Twister,40,10,100,Dragon
        ///Whirlpool,35,15,85,Water
        ///Ice Fang,65,12,95,Ice
        ///Brine,65,14,100,Water
        ///Waterwall,80,10,100,Water
        ///Crunch,80,11,100,Dark
        ///Aqua Tail,90,13,90,Water
        ///Hydro Pump,110,9,80,Water
        ///Hurricane,110,10,70,Flying
        ///Thrash,120,9,100,Normal
        ///Hyper Beam,150,5,90,Normal.
        /// </summary>
        public static string Gyarados {
            get {
                return ResourceManager.GetString("Gyarados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à gtg
        ///gtgt
        ///gt
        ///gtg
        ///tg
        ///tg.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Potion,20,1
        ///Max Potion,500,1
        ///Hyper Potion,200,1
        ///Revive,1,1
        ///Antidote,0,1
        ///Revive,100,1
        ///Super Potion,100,1
        ///Pokéblock,20,5.
        /// </summary>
        public static string InventoryItems {
            get {
                return ResourceManager.GetString("InventoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Combat,120,10,100,Fighting
        ///Meteor Mash,90,10,90,Steel
        ///Dragon Pulse,85,10,100,Dragon
        ///Extreme Speed,80,10,100,Normal
        ///Aura Sphere,80,10,100,Fighting
        ///Force Palm,60,10,100,Fighting
        ///Metal Claw,50,10,95,Steel
        ///Power Punch,40,10,100,Fighting
        ///Rock Smash,40,10,100,Fighting
        ///Quick Attack,40,10,100,Normal
        ///Feint,30,10,100,Normal
        ///Bone Rush,25,10,90,Ground.
        /// </summary>
        public static string Lucario {
            get {
                return ResourceManager.GetString("Lucario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confusion,50,15,100,PSYCHIC
        ///Ancient Power,60,15,100,ROCK
        ///Psycho Cut,70,15,100,PSYCHIC
        ///Psystrike,100,20,100,PSYCHIC.
        /// </summary>
        public static string Mewtwo {
            get {
                return ResourceManager.GetString("Mewtwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rock Throw,50,10,85,Rock
        ///Tackle,40,10,100,Normal
        ///Smack Down,50,10,100,Rock
        ///Dragon Breath,60,10,100,Dragon
        ///Rock Slide,75,9,90,Rock
        ///Stand Tomb,35,10,85,Ground
        ///Iron Tail,100,9,100,Steel
        ///Dig Dig,80,9,100,Ground
        ///Slam,80,10,75,Normal
        ///Stone Edge,100,9,80,Rock
        ///Double Edge,120,7,100,Normal
        ///Earthquake,100,5,100,Ground.
        /// </summary>
        public static string Onix {
            get {
                return ResourceManager.GetString("Onix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick Attack,40,10,100,Normal
        ///Thunder Shock,40,12,100,Electric
        ///Spark,65,14,100,Electric
        ///Thunderbolt,90,10,100,Electric
        ///Thunder,110,8,70,Electric
        ///Thunder Punch,75,9,100,Electric.
        /// </summary>
        public static string Pikachu {
            get {
                return ResourceManager.GetString("Pikachu", resourceCulture);
            }
        }
    }
}
